# Use the official Jupyter base image
FROM jupyter/scipy-notebook:latest

# Install any additional Python packages you need
RUN pip install --no-cache-dir ollama python-dotenv

# Set the working directory
WORKDIR /Users/valeriauribe/Github/welcome-to-docker/jupyter
