# Use the base Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r /app/requirements.txt


# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 7860

# Run the application
CMD ["python", "whisper.py"]